font_family      family="MesloLGSDZ Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16.0

map cmd+left  send_text all \x01
map cmd+right send_text all \x05
map alt+left  send_text all \x1bb
map alt+right send_text all \x1bf
map cmd+backspace send_text all \x15
map alt+backspace send_text all \x1b\x7f

copy_on_select yes
cursor_shape block

shell_integration enabled
shell_integration no-cursor
scrollback_lines -1
map shift+cmd+up scroll_to_prompt -1 2
map shift+cmd+down scroll_to_prompt 1 2
map shift+cmd+l scroll_to_prompt 0
map cmd+up scroll_home
map cmd+down scroll_end
map cmd+f search_scrollback
map cmd+alt+f show_scrollback
map shift+cmd+g show_last_command_output

enabled_layouts vertical,stack
map cmd+shift+d new_window
map cmd+shift+enter toggle_layout stack
map cmd+[ previous_window
map cmd+] next_window

map cmd+t new_tab
map cmd+w close_tab
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
