[tools]
bun = "latest"
go = "latest"
java = "latest"
node = "latest"
opencode = "latest"
pnpm = "latest"
python = "latest"
turso = "latest"
uv = "latest"

[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["java"]
