[ids]
*

[main]

# Physical Cmd -> Ctrl
# Physical Ctrl -> Super
control = layer(meta)
meta = layer(control)


# macOS Command navigation
[control]

left = home
right = end
up = C-home
down = C-end

backspace = macro(S-home backspace)


# macOS Option navigation
[alt]

left = C-left
right = C-right

backspace = C-backspace


# macOS Command + Shift selection
[control+shift]

left = S-home
right = S-end
up = C-S-home
down = C-S-end


# macOS Option + Shift selection
[alt+shift]

left = C-S-left
right = C-S-right
